### ISSUE TITLE
Collision detection bug when wallrunning across corners

### ISSUE THREAD

**Issue by robalni** [blue-nebula/base#151]
This is a bug that has annoyed me for years and I think it's time to fix it.

**Summary description:** Wallruns end when you run across corners in the (-x,-y) orientation if the cube behind the corner has a visible face.

**Long description:**

![20200725134131](https://user-images.githubusercontent.com/1399719/88456280-afdd3d80-ce7c-11ea-8091-0e1c14eec2d6.png)

Map file seen in the image: [cornerbug.zip](https://github.com/blue-nebula/base/files/4975481/cornerbug.zip)

If you try to wallrun on the yellow walls that you can see in the image (run across the corner in the middle by tapping q once, not holding it) it will work on all walls except for the one in the (-x,-y) direction; on that wall you will fall down when you reach the corner in the middle. However the wallrun does work if you cover the faces of the cube behind the wall (as done with the purple wall in the image).

**Why I think it happens:**

The reason for this is that when you reach the corner, you collide with the block behind the wall. When you run on the other walls, you actually touch the blocks behind those walls too but it only counts as collision on the (-x,-y) wall because of the order in which the game checks collision with a cube's children, negative before positive, and therefore it finds a collision with the block behind the wall before it checks the walls because the block behind has a more negative x and y coordinate than the walls themselves.

There is some code in the game that ignores collisions with cube faces that are not visible (because they are touching other cubes) so you might think that this collision should be ignored since the faces of the cube behind the wall that you are closest to are not visible. That's correct; those faces *are* ignored. The collision actually happens with the other faces of that cube (e.g. the top one). This can be demonstrated by occluding all faces of the cube like you can see at the purple wall in the background. If you do that you will see that wallruns work just fine. Another way to fix it is of course to remove the cube behind the wall.

So how is it possible to collide with e.g. the top face of the cube when you're not even close to that face? When the game decides which face you collided with, it looks for the face that you are closest to, but the face check is completely skipped for the faces that are not visible and therefore the only visible faces will be used. There is a line of code that looks like it's supposed to avoid cases like this one. The following two lines are from the definition of macro CHECKSIDE in engine/physics.cpp:

```
        if(!dir.iszero()) \
            if(d->type<ENT_CAMERA && dotval < 0 && dist < margin) continue; \
```

`continue` means that the face is skipped. `dotval` is `dir.[xyz]` or `-dir.[xyz]` depending on the face. `dir` is the velocity of the player. This line of code actually does the job; the only problem is that `dir` is sometimes 0, even when the player is moving, which will cause this line to be skipped. The reason that `dir` can be 0 is that the `collide` function is sometimes called without specifying it, like in this code line in game/physics.cpp:

```
                bool collided = collide(d);
```

The velocity (`dir`) needs to be the second argument to `collide`, otherwise it will get the default value of (0, 0, 0) and that will cause the collision check to not skip the faces it should skip. It's worth noting that the second argument was removed in commit 3027c0244ac6aa604477d1d06f319a4296e90b3e for unknown reasons.

**Comment by MoonPadUSer** [comment]
tbh I've never personally encountered this bug, but I think we should definitely first figure out the reasons why the second argument was removed in the first place, as we could otherwise easily introduce a "sleeping giant" bug (I like to call it like that, basically a bug that goes unoticed for a long time but causes unknowingly a lot of problems)

**Comment by robalni** [comment]
The bug happens sometimes to me when I do races (especially in testchamber on the wall before the first narrow vertical hole) and it causes me to lose speed and lose the ability to get a second jump after the jump from the wall.

I have asked @qreeves about it in email but haven't seen a reply yet. Maybe he will see this issue now too.

**Comment by MoonPadUSer** [comment]
ehm, I can actually ask him right away on discord...

**Comment by MoonPadUSer** [comment]
This is Quins answer:
the code has since been rewritten in RE, mostly with Tesseract extensions
the reason `dir` was removed from the function parameters is because we're already adding the direction to `d->o`, so you end up duplicating projection and can lead to some checks starting inside the wall and trying to continue through it
what you wanna do mostly is check `collideinside` after running `collide()`, but I'm not sure if that's a Tesseract thing or not
but should be fairly easy to port the updates to `engine/physics.cpp`
the engine does make a note of collisions which are inside objects, but to do it by default would mean you'd get stuck when the vector wanders inside things
which can happen a lot
like stair smoothing and sliding against walls, your position actually always ends up inside the geometry

Ok, this is the answer I got from him, I hope it can help you (I haven't looked to deep into that specific code myself)

**Comment by robalni** [comment]
Checking `collideinside` is already done. The problem is that it is only set if none of the faces caused a collision in CHECKSIDE and this bug happens because one of them does.

A different way to solve this is to make sure `collideinside` will be non-0 even when dir is 0, by not requiring dir to be non-0, like in 46741b89f7a6c690020e5a92909535cd8dca9303. Would this be better?

**Comment by robalni** [comment]
It seems this is the bug that makes you get stuck on the slopes near the bases in deli. You collide with the cube below the slope. The only problem there is that the face you collide with is visible since the thickness of the slope doesn't cover all of it so the fixes I have thought about for this bug will not fix that. Maybe we will have to change the map in that case.
