### ISSUE TITLE
Game locks up with one core maxed out

### ISSUE THREAD

**Issue by voidanix** [blue-nebula/base#21]
**First seen in**: current master

**Observation**: the game would freeze with one core on 100% usage until its killed

**How to reproduce**:
1. Play normally
2. When spectating, switch cameras and sometimes the bug will trigger (cannot be reproduced easily)

I searched the issue list and checked that this is not a duplicate :white_check_mark: 
I tried to rename my *config.cfg*, and the problem also occurs with default settings :white_check_mark:

**Comment by TheAssassin** [comment]
Sounds like some sort of livelock. I observed that behavior years ago the last time. The question is, how can we track down the issue? I guess either through running it in a debugger or by adding logging.

**Comment by bmorel** [comment]
This will be hard, since our current code base uses a custom vector implementation that has some quirks (structures and so public access, but it seems it has not been abused, disown() method, only used in command.cpp in 4 places by luck, and other minor things).
I am actually trying to make valgrind and google-perftools silent as well as moving toward STL containers as long as there is no measurable and negative performance impact.
I think this might help reducing the number of those issues.

To be actually able to fix the problem, we would need someone to experience the bug with a debugging version, and put a debugger there. Instrumentation and logging would make a lot of noise and I doubt that would be really efficient.

**Comment by qreeves** [comment]
There are tons of issues with SpecTV in the 1.6 codebase that resulted in this. I have since rewritten it in 2.0, but it uses the new rail system to move cameras around rather than random entities, but your main culprit here is the code from `src/game/game.cpp` in and around the `cameratv()` function.

**Comment by robalni** [comment]
Does this happen when watching through SpecTV or when following a player?

**Comment by voidanix** [comment]
This has never happened again for quite some time... closing.
