### ISSUE TITLE
Sorry for ask this question.

### ISSUE THREAD

**Issue by cantianz** [blue-nebula/base#237]
VERY SORRY FOR ASK THIS. But I want to know why create this fork, is their developer think some issues is not a issue, in other words, they think they dont have problem?

**Comment by cantianz** [comment]
I ask this because I just been annoyed from their developers.

**Comment by TheAssassin** [comment]
This fork was created in order to be able to continue development and maintenance on the old Red Eclipse 1.x version. It was created by members of the community which prefers this version over the current Red Eclipse 2.x for various reasons.

We chose to found a new team that is independent of the people behind Red Eclipse in its decisions and infrastructure to be able to make own decisions with regards to the design and future development of the game. Therefore, we also adopted a new name and called the project Blue Nebula.

Please feel free to join our Chat `#blue-nebula` on [Libera.Chat](https://libera.chat). You can use the [webchat](https://go.blue-nebula.org/irc-webchat).

**Comment by cantianz** [comment]
To be honest, first, thank you for you reply. And you are better than qreevs, he thinks this is not a issue, that is not a issue, all is excepted.

**Comment by cantianz** [comment]
You can delete this if you dislike.
