### ISSUE TITLE
Review intellectual property and copyright violations

### ISSUE THREAD

**Issue by qreeves** [blue-nebula/base#25]
As per the [Red Eclipse Mark Policy](https://github.com/redeclipse/base/blob/master/doc/trademark.txt) (a copy of which you have in this repository), I hereby ask that you respect the intellectual property and rights of the Red Eclipse project and remove our copyrighted materials.

- The name "Red Eclipse Legacy" is not a permitted use of the "Red Eclipse" name, as it is likely to cause confusion with the false belief it is an official product by the Red Eclipse team and in turn harms the community. Part of our plan included re-releasing v1.6 on Steam under the name "Red Eclipse Legacy" at a later point (and is already available on GameJolt under that branding), which has now been confused by the existence of this improperly named fork.

- The files "icon.png" and "logo.png", along with all derivatives and imagery, are provided under the provisions of the Red Eclipse Mark Policy. The use of these images in this project is not only illegal, but it serves to further confuse people as to the nature of the project.

I don't much appreciate people trying to piggyback on the hard work I've put in over the last decade. A lot of time and effort has gone into establishing the Red Eclipse brand and related intellectual properties, and I've been more than generous in making sure everything you need to make a fork is free and open source - but I had one simple rule: _please don't use our name and logos_. You of all people should have respected that.

I'm trying not to get upset and do the right thing by coming and asking nicely. I'm not interested in an argument or a debate on the issue. Should the matter not be resolved within 10 business days (close of business 11th June 2020), I will unfortunately have to take further action in order to protect the interests of the Red Eclipse project.

**Comment by Lyberta** [comment]
[There is no such thing as intellectual property.](https://www.gnu.org/philosophy/not-ipr.html) It is a lie perpetuated by evil and greedy people who try to equate copyright infringement (among other things) to theft which is nonsense. You only have trademark rights.

**Comment by TheAssassin** [comment]
Hey @qreeves, thanks for starting a dialog first. We are in the process of renaming, but due to lack of personpower, this'll take a couple of days from now. We had set up a public poll [in our wiki](https://github.com/redeclipse-legacy/base/wiki/Name-Suggestions) and this poll closed yesterday, now internal review and discussion is in process. The name "Red Eclipse Legacy" will, along with the logo and name, be replaced another one. Your deadline is roughly 2 weeks away, we should be done by then. We can keep this issue updated.
The decision to rename the project was not done with the mark policy in mind but by our interest in creating a custom branding and ecosystem. This should ensure a peaceful and well distinguished coexistence with your project(s). So far, the game in our fork is still *the game*, it has not been modified yet really, and your reputation should not be endangered in any way as far as we are concerned.

Regarding the icons: we had a look at those files again, and indeed, those are apparently not freely licensed, but subject to this mark policy. The mark policy therefore becomes a copyright/license file in this context. In order to avoid any issues, we've always planned to replace those files, too. Thanks for highlighting this explicitly.

There is no need for a (legal) debate or discussion at all, don't worry. We we have made the strategic decision to rebrand our fork even before forking in the first place. We hope the plan above is satisfying. We have taken into account your deadline and will try to turn off any (potential) violations by then. As you could hopefully read from our [README](https://github.com/redeclipse-legacy/base/blob/master/README.md#red-eclipse-legacy), we have no bad intentions at all, and respect and value your work. In fact, we highlight that explicitly.

Please don't hesitate to get in touch for further questions.

*P.S.: We could not know you were planning to use that exact same name as well. That was a coincidence, really. We have avoided using the name in any public communication outside our GitHub project so far, and will inform people on request about the differences between your Legacy project and our `<insert name here later>`.*

**Comment by qreeves** [comment]
@TheAssassin No problem, I just figured I should clear this up before it became a bigger issue. I have no problem at all with friendly forks, and actively encourage everyone to do it if that's what they want to do, hence why I worked so hard to make everything else open licensed.

I know you couldn't have guessed we'd try to use the same name, and I was more trying to show how using "Red Eclipse" at all in the title interferes with our "business" (if you call it that, lol).

Thanks for being candid and open about this, open source is about being in this together for the better of everyone, and being able to sort things out between ourselves should be something we strive for in that environment. I'm not trying to be a greedy corporation, just protecting the community I built.

In legal terms, the plan to change the name and related assets technically resolves the complaint, which means the "10 business day" deadline is replaced by "taking said action within a reasonable amount of time", so I wouldn't sweat too much about rushing around, just try to ensure it gets done.

**Comment by TheAssassin** [comment]
Just as promised, here's an update: We chose the name "Blue Nebula". The GitHub organization has been renamed already, we have to change the name in some READMEs and also we don't have a new logo yet. It's all work in progress, I'll keep this issue updated.

**Comment by qreeves** [comment]
Cool. What colour blue are you going with?

**Comment by TheAssassin** [comment]
Probably same dark blue of any kind? We just chose "blue" for now, and have to tinker a bit. I could imagine something around #0000aa or #0070cc to #0085aa. It'll depend on the logo and backgrounds.

**Comment by bmorel** [comment]
TheAssassin, I was more in favor of dark blue, but I'm just thinking that, actually, "cool" blue nuances could be usable. In the 1st meaning of cool, of course, aka cold.

Oh, and: welcome qreeves, and thanks for building RE. Since you intend to still improve RE 1.6 (with steam support it seems?), maybe we could exchange some patches? I think some of mines could be adapted to reduce memory leaks for example (shown by google-perftools and valgrind, not imaginary ones).

**Comment by qreeves** [comment]
Depends if they still apply in 2.0 or not, as I'll be doing most of the backporting directly from there and I know we've squashed quite a number of those issues since 1.6 released. I haven't solidified any ideas yet, but I'm considering keeping the two codebases in tighter sync, minus gameplay and renderer changes, so that future maintenance is much easier.

**Comment by TheAssassin** [comment]
I have taken a few hours and with great care tried to replace all occasions of "Red Eclipse" in the base repository. This is where the name is used most of the time.

We still have to design a new logo and update the `textures` submodule accordingly. There might be screenshots and maybe old maps with the old logo, but I don't think those will affect your branding in any way. However, the long term goal is to replace those as well. We already replaced one texture which consisted of basically the logo only. I'll update this post once we have that logo in place. We're looking for someone to help design one and create SVGs etc. for it.

Regarding the patches, our code base deviates more and more from RE 1.6 and therefore probably even more from 2.0. If any of our work is useful to you, please feel free to use it (under the licenses, of course). Like you, we publish it as freely as possible.

**Comment by SalatielSauer** [comment]
Hey, I saw quin's post somewhere, do you still need a logo?
If so, feel free to use these assets below as placeholders, until you find something else :)
![bluenebula_banner3](https://user-images.githubusercontent.com/9287152/83341281-fc126400-a2b7-11ea-86ba-730f64cab90a.png)
![bluenebula_banner2](https://user-images.githubusercontent.com/9287152/83341289-22380400-a2b8-11ea-86cb-5033c7869148.png)
The font is called "[Nebula](https://www.dafont.com/pt/nebula-2.font)" and is free for non-commercial use.

![bluenebula_banner0](https://user-images.githubusercontent.com/9287152/83341303-3da30f00-a2b8-11ea-9125-fe4be6bbf7ea.png)
![bluenebula_img](https://user-images.githubusercontent.com/9287152/83341422-bfe00300-a2b9-11ea-80bc-35a405b07124.png)
![bluenebula_banner4](https://user-images.githubusercontent.com/9287152/83341442-f0c03800-a2b9-11ea-8c79-16dee7c514cb.png)
https://imgur.com/a/irPV5FJ

**Comment by Lyberta** [comment]
I'm don't think using proprietary font is a good idea.

**Comment by TheAssassin** [comment]
Please open a new issue for this matter, thanks.

**Comment by qreeves** [comment]
Probably my fault, sorry. I put out some feelers to see if there was anyone up to making you guys a new logo and referenced this issue as context. I'll close the issue now. Thanks for helping out @SalatielSauer 😄

**Comment by TheAssassin** [comment]
Thanks @qreeves for trying to help out. @SalatielSauer's offer is highly appreciated. We consider the logo proposal, we need to clarify questions of licensing etc. first, though. Also, we're seeking for a vector graphics, but as said, I'll open another issue for that.

The logo appears to be the last remaining bit that needs to be replaced. Once done, we should've finished the transition. If you ever spot any incorrectness regarding licensing notices (I took great care to represent your copyright appropriately, but IANAL), please don't hesitate to reach out. We can likely sort out all issues quickly. Thanks again for starting the dialog first.
